# Generated by Django 4.0.6 on 2022-08-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('leyenda', models.CharField(max_length=300)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
