# Generated by Django 4.0.6 on 2022-08-31 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmensajes', '0002_remove_mensaje_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='leyenda',
            new_name='mensaje',
        ),
    ]
