# Generated by Django 4.0.6 on 2022-09-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmensajes', '0004_rename_mensaje_mensaje_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='texto',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
