# Generated by Django 4.0.6 on 2022-09-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmensajes', '0005_alter_mensaje_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='usuario',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
