# Generated by Django 4.0.6 on 2022-08-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0002_cliente_colaborador_proyecto_requerimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
