# Generated by Django 4.0.6 on 2022-08-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appentrega', '0004_alter_proyecto_costo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_id',
            new_name='rut',
        ),
    ]
